### PR TITLE
OAR enhancements, including support for recursive scan/loading and IW OARs opt-in

### PR DESCRIPTION
**Pull request by appurist**
While this seems very specific, there is a ton of generally useful enhancements to the regular OAR code too. It now supports recursively deserializing nested objects, restoring them regardless of how deeply nested the objects are.  It also supports filtering of OAR content based on creator, the creation of modified (nested) objects, serialization of those nested objects, creation of new assets for those modified nested objects, and updating of the Contents list of the parent objects.

Known limitation: I haven't done the work to support _coalesced_ (multi-object) task inventory items.  There's an error report now where that is detected and skipped.  That work is not a large variation on the current code so I wanted to get this PR submitted asap for review since it is some major updates to all of this code.  That can be done in a separate Part 2 PR in the future.

### CODE REVIEW

**Comment by appurist** [comment]
This is ready for merge now. Full filtering by creator, fully recursive scanning and restoration of Contents in OAR files, progress updates on loading, stats, and a `debug oars 0|1|2` command.

**Comment by appurist** [comment]
Note that there are so many changes in `OpenSim/Region/CoreModules/World/Archiver/ArchiveReadRequest.cs` that GitHub won't show the differences by default.  About 1100 lines added there alone, and another 300 changed elsewhere...

**Comment by kf6kjg** [comment]
Yeah, I expected that limit. I'll probably be reviewing via GitKraken :P

**Comment by kf6kjg** [comment]
Looks like there's a merge conflict.  I tried a simple rebase but couldn't easily get past some of the conflicts due to not knowing what was going on and why.

Also I noticed that he new OAR commands have "iw" prefixes - as opposed to "hal" prefixes or no prefixes.  I think you may have mentioned this before in chat, but I forgot the reasoning... :/ If this is to be for more general consumption I'd prefer non-grid-specific prefixing.

**Comment by appurist** [comment]
Another approach would be for Islandz to fork the code back again, but I see this more as something that just needs some temporary code (along with a bunch of base abilities we get with it) that can be included for some number of months and then eventually replaced perhaps with something more general-purpose and the new commands part of this PR would probably just go away.  Yes that's a bit of technical debt but is for a very specific purpose, avoids a fork, maintaining the single common codebase for now, and can go away once this situation is considered resolved.

**Comment by kf6kjg** [comment]
In principle I'd rather not have grid specific code being integrated without being made more general. However, I also have learnt pragmatism. I'll merge with the understanding that these commands are not expected to be supported, and have a limited lifetime; that the intent is to use the logic therein to enhance other related code soon.

**Comment by kf6kjg** [comment]
Released (finally) in v0.9.42.

**Pull request merged**
