### PR TITLE
Drop duplicate/incorrect RDB table definitions from inworldz-core-base.sql and unused ones.

### PR DESCRIPTION
**Pull request by appurist**
I've done a full review of both `inworldz-core-base.sql` and `inworldz-rdb-base.sql`.

Tables `primitems`, `prims`, `primshapes` have correct definitions in in `inworldz-rdb-base.sql`, but are duplicated with incorrect definitions in `inworldz-core-base.sql`.  These extra, incorrect definitions have been removed.

Also removed unused tables `allparcels`, `parcels`, `userfriends_old`, `userprefs_bak`, and `users_bak` that were just historical baggage and technical debt being dragged along from early InWorldz days (or earlier).  (The `parcels` table is now `land`, and present in the region database (RDB) schema.)

### CODE REVIEW

**Comment by appurist** [comment]
Copying @sonjamichelle on this, who just fixed the last problem in the RDB sql schema file, so no further changes are needed there.

**Comment by kf6kjg** [comment]
Oh good! I hate debt...

**Comment by appurist** [comment]
I've updated the wiki page to include an overview and description of the separation of core and RDB tables. I think that's about as much as we can do until someone can step in to the hc_database.exe utility and update it, but there is much more that can be done there.  See the last paragraph below:
Core and RDB Database Schemas

**Comment by kf6kjg** [comment]
Released (finally) in v0.9.42.

**Pull request merged**
