### PR TITLE
Async cleanup

### PR DESCRIPTION
**Pull request by kf6kjg**
And this I gave a quick test in full grid mode: ran all 3 grid services and a region on Windows, logged in with Firestorm and tested a few scripts, physics thingies etc.

No errors found, which is good.

Two possible results I predict, and both might happen: some of the occasional glitches will disappear due to less thread pool starvation, and there might be an increase in service/region irrecoverable crashes due to exceptions that were hidden behind an obscure .NET behavior are now able to be seen.  That latter will result in bug fixes and far better software, so I'm OK with it.

Please review my commit messages for some of the details and reasoning.

### CODE REVIEW

**Comment by kf6kjg** [comment]
A potentially helpful tool found by @mdickson : https://www.ryadel.com/en/asyncutil-c-helper-class-async-method-sync-result-wait/

**Comment by kf6kjg** [comment]
@appurist I know it's been a couple years since we both last looked at this. Could you look it over again?

IIRC there's a utility in the system for fire-and-forget operations to use if they intend to do such things.  In my current opinion calling an unawaited async method in C# is hazardous due to the loss of exceptions: an unawaited async method call will never report any errors that might have happened inside it, thus hiding bugs. I suspect this is why I elevated CS4014 to an error instead of a warning.

While I do agree that some of these sites may have intentionally used the technique as a fakie "fire-and-forget" I doubt that the loss of exception detection was intended. Due to the lack of code comments about the technique I'm lead to believe that this wasn't often intentional, but accidental.  It's possible that functions that were originally syncronous became unintentionally async when someone added an async call inside of a deeply nested callsite.

**Review by appurist — APPROVED** [review]
Looks great.

**Comment by kf6kjg** [comment]
Now the commit messages have the correct grammar to show in the logs.

**Pull request merged**
