### PR TITLE
Pr102 fix

### PR DESCRIPTION
**Pull request by emperorstarfinder**
This PR fixes a crash caused by the missing water texture from PR https://github.com/HalcyonGrid/halcyon/pull/102

- It appears the Water texture the viewers need when the viewer has a rendering of water disabled did not make it into the PR.
- Make sure the water texture is listed in TexturesLibraryItems.xml

### CODE REVIEW

**Review by appurist — APPROVED** [review]
Good catch!

**Comment by Vinhold** [comment]
Running the release Halcyon.0.9.44 threw this exception:
Halcyon 0.9.44 Error:
APPLICATION EXCEPTION DETECTED: System.UnhandledExceptionEventArgs

Exception: System.IO.FileNotFoundException: Could not find file 'C:\3DWorldz\Wor
ld\9500\assets\TexturesAssetSet\43c32285-d658-1793-c123-bf86315de055.jp2'.
File name: 'C:\3DWorldz\World\9500\assets\TexturesAssetSet\43c32285-d658-1793-c1
23-bf86315de055.jp2'

Actual filename:
43c32285-d658-1793-c123-bf86315de055.j2c

I changed the name of the file to 43c32285-d658-1793-c123-bf86315de055.jp2 and Halcyon loaded correctly so this is its only error in starting up.

**Comment by kf6kjg** [comment]
New workarounds:
* Rename the `43c32285-d658-1793-c123-bf86315de055.j2c` file to `43c32285-d658-1793-c123-bf86315de055.jp2`,
* Or edit the file `bin\assets\TexturesAssetSet\TexturesAssetSet.xml` and in the section `<Section Name="Water">` change `43c32285-d658-1793-c123-bf86315de055.jp2` to `43c32285-d658-1793-c123-bf86315de055.j2c`

**Comment by emperorstarfinder** [comment]
no workarounds needed folks, a fix is already incoming.

**Comment by Vinhold** [comment]
Why is that entry not a named texture entry also? I put the UUID on a cube to see what it was and its a dark blue marble sort of appearance.

**Comment by emperorstarfinder** [comment]
It is supposed to be the water texture that viewers need when the water is set to an invisible in-world.  Can you send me a picture of what you are seeing via discord?

**Comment by Vinhold** [comment]
Done! :)

**Comment by Vinhold** [comment]
Some oddities. Not finding where to post this stuff!
Halcyon Prerelease 0.9.45:
The regions load way faster than expected, not appearing to load the Library XML or that process has been improved a 100% for speed operation! The file AssetSets.xml.loaded is being created on region startup. But the long wait while loading does not appear to happen. 

I do not know what the name of the default water that was added is. No water named item appears in the Library textures list.

I did notice that the Library scripts list contains a folder for OpenSim Specific Scripts
containing osSetDynamicTextureData() or osSetDynamicTextureURL(). Of course none of the three listed scripts will work in Halcyon as is. Not sure those functions even exist in Halcyon. So I recommend that folder entry and referenced script assets be removed before official release.

**Comment by kf6kjg** [comment]
You'd start by posting commentary in the Discord server. Issue comments should be limited to only info relevant directly to the issue.

**Comment by emperorstarfinder** [comment]
As I already explained to Vinhold via discord, the water texture does not need to be listed in the TexturesLibrary.xml file.  It is only intended to be used by the viewer in the event the user disables transparent water settings via the viewer preferences.  

I did not optimize anything else as far as the loading of the libraries so the fact is loading faster is a good thing.  

The OpenSim Specific scripts probably can be safely removed as my understanding is that OSSL support was removed when InWorldz replaced the scripting engine with Phlox.  So the three OSSL scripts are not needed.

**Pull request merged**
