### PR TITLE
Fix for the 26 items max task inventory bug. 

### PR DESCRIPTION
**Pull request by mdickson**
Credit to Hyacinth Jean for sleuthing the fix and Jim Tarber for supplying it to Skye-Grid.  This should still be tested before integration into a release but as you can see it's a fairly straightforward fix.

### CODE REVIEW

**Comment by mdickson** [comment]
This does not work on the newly running Skye-Grid.   I'm sure its my error but looking into more.

**Comment by emperorstarfinder** [comment]
Ideally, you want to test to confirm that it is working before you submit the PR.  

Because you are actually modifying your fork, based on what you see to be fit for what you're doing with your grid, it is important to keep in mind you want to test against a clean unmodified copy of the HalcyonGrid source code and use a clean fork that your not modifying for your grid when doing the PR.  This way you can be sure you submit clean valid code that works with HalcyonGrid's version and will avoid accidentally sending commits to HalcyonGrid that are version specific to what you're doing on your grid and not intended for HalcyonGrid.  It also helps HalcyonGrid project managers keep and maintain their projects in a clean way.

**Comment by mdickson** [comment]
Thanks for the CICD-101.  This change was against a clean copy of upstream.    I pushed the PR because I had received a copy of the patch and hadn't yet seen anything by others who claim to have "fixed" it.  I'll close this and resubmit later after testing if no one else steps forward with a fix for it.

**Comment by Yichard** [comment]
I personally tested the fix in Enchanted. It worked. However I am not sure they started from a clean fork, and actually they messed with the version numbering.

**Pull request closed without merging**
