### PR TITLE
CI/CD rebuild from scratch

### PR DESCRIPTION
**Pull request by kf6kjg**
AppVeyor is no longer the only player on the market that can do the job.  In fact GitHub has been able to handle this for some time.

While this IS a C# project, I did add a veneer of NodeJS Typescript tooling to work with the CI/CD systems. It'd be a fun mental exercise to rebuild all the scripts in C#, but not one I have time for ATM.

### CODE REVIEW

**Review by appurist — APPROVED** [review]

**Comment by appurist** [comment]
This not only looks great but there are several points of good cleverness within.

I'm probably not the best to review GitHub Actions or the GH CI/CD, but I'm familiar enough and take a good look at every line and absolutely nothing stood out, other than the following two comments (which aren't problems with the PR):
- the `package.json` specifies `"private": true` (which may be irrelevant here) as the repo is public and you aren't intending to publish it on npmjs.org, but for my understanding of it, ideally it should match unless you're specifically trying to prevent publishing.
- FYI, I believe any build on Ubuntu 20.04 won't load on RHEL 7 or CentOS 7 (the most recent LTS version) due to newer CXXABI requirements. In some enterprise environments, this can be a showstopper, but for Halcyon I don't see this as a problem, a.k.a. "tough" :)

Looks good, and pretty extensive work here!

**Comment by kf6kjg** [comment]
> specifically trying to prevent publishing.
That.

>  CXXABI
Good thing this is DotNet.

:D

**Comment by appurist** [comment]
Haha, good point.

**Comment by kf6kjg** [comment]
Released in v0.9.42.

**Pull request merged**
